version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - PierreBrisorgueil
  ignore:
  - dependency-name: snyk
    versions:
    - 1.447.0
    - 1.448.0
    - 1.450.0
    - 1.457.0
    - 1.464.0
    - 1.486.0
    - 1.495.0
    - 1.503.0
    - 1.505.0
    - 1.514.0
    - 1.518.0
    - 1.521.0
    - 1.522.0
    - 1.526.0
    - 1.528.0
    - 1.532.0
    - 1.538.0
    - 1.563.0
    - 1.566.0
    - 1.570.0
